# fly.toml app configuration file generated for misty-night-5925 on 2023-05-17T14:36:20+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "misty-night-5925"
primary_region = "hkg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
